# Generated by Django 3.0.3 on 2020-03-11 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hostpot',
            fields=[
                ('nome', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('mac', models.CharField(max_length=60)),
                ('rua', models.CharField(max_length=60)),
                ('bairro', models.CharField(max_length=60)),
                ('cidade', models.CharField(max_length=60)),
                ('estado', models.CharField(max_length=60)),
            ],
        ),
    ]
