# Generated by Django 3.0.3 on 2020-03-11 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostpot',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='hostpot',
            name='estado',
            field=models.CharField(choices=[('ac', 'AC'), ('al', 'AL'), ('ap', 'AP'), ('am', 'AM'), ('ba', 'BA'), ('ce', 'CE'), ('df', 'DF'), ('es', 'ES'), ('go', 'GO'), ('ma', 'MA'), ('mt', 'MT'), ('ms', 'MS'), ('mg', 'MG'), ('pa', 'PA'), ('pb', 'PB'), ('pr', 'PR'), ('pe', 'PE'), ('pi', 'PI'), ('rj', 'RJ'), ('rn', 'RN'), ('rs', 'RS'), ('ro', 'RO'), ('rr', 'RR'), ('sc', 'SC'), ('sp', 'SP'), ('se', 'SE')], default='pa', max_length=60),
        ),
    ]
