# Generated by Django 3.0.3 on 2020-03-11 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_auto_20200311_1331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hostpot',
            old_name='status',
            new_name='ativo',
        ),
    ]
