# Generated by Django 3.0.3 on 2020-03-12 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_auto_20200311_1428'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hostpot',
            old_name='mac',
            new_name='endereco_mac',
        ),
    ]
