# Generated by Django 3.0.3 on 2020-03-09 12:38

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hostpot',
            fields=[
                ('nome', models.CharField(max_length=60)),
                ('mac', models.CharField(max_length=60, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('nome', models.CharField(max_length=60)),
                ('telefone', phonenumber_field.modelfields.PhoneNumberField(max_length=19, primary_key=True, region='BR', serialize=False)),
                ('bairro', models.CharField(max_length=60)),
                ('cidade', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='s', to='session.Lead')),
            ],
        ),
    ]
