# Generated by Django 3.0.3 on 2020-03-09 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostpot',
            name='bairro',
            field=models.CharField(default=22, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hostpot',
            name='cidade',
            field=models.CharField(default=22, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hostpot',
            name='estado',
            field=models.CharField(default=22, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hostpot',
            name='rua',
            field=models.CharField(default=22, max_length=60),
            preserve_default=False,
        ),
    ]
